name: DEV Tester

on: 
  repository_dispatch:
    types: 
      - test-run
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test in dev1
        run: |
            curl --location --output artifacts.zip --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_PRIVATE_TOKEN }}" "https://gitlab.com/api/v4/projects/20170807/jobs/732184328/artifacts"
            unzip -ao artifacts.zip
            rm artifacts.zip
            fastlane dev_tester amount:${{ github.event.client_payload.amount }} cardNumber:${{ github.event.client_payload.cardNumber }}
